dependencies:
  - name: reqsubchart_b_1
    version: 0.1.0
    repository: file://helm-charts/reqsubchart_b_1
  - name: reqsubchart_b_2
    version: 0.1.0
    repository: file://helm-charts/reqsubchart_b_2
