dependencies:
  - name: reqsubchart_a_1
    version: 0.1.0
    repository: file://helm-charts/reqsubchart_a_1
  - name: reqsubchart_a_2
    version: 0.1.0
    repository: file://helm-charts/reqsubchart_a_2
